default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pasr_development

test:
  <<: *default
  database: pasr_test

production:
  <<: *default
  database: pasr_production
  username: pasr
  password: <%= ENV['PASR_DATABASE_PASSWORD'] %>
